version: "3.8"

networks:
  front-connection:
    driver: bridge
  db-connection:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports: 
      - "80:80/tcp"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - front-connection
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - everytown
      - backend
      - imageserver
  everytown:
    build:
      context: ./client/frontProject
      dockerfile: Dockerfile
    container_name: everytown
    restart: always
    expose:
      - "5000"
    networks:
      - front-connection
  backend:
    networks:
      - front-connection
    build:
      context: ./server/backendProject
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - 7777:7777
    depends_on:
      - mysqldb
  mysqldb:
    container_name : mysqldb
    image: "mysql:5.7"
    restart: always
    ports:
      - 3308:3306
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --range_optimizer_max_mem_size=16777216
    environment:
      MYSQL_DATABASE : everytown
      MYSQL_USER: everytown
      MYSQL_PASSWORD: everytown
      MYSQL_ROOT_PASSWORD: everytown
    networks:
      - front-connection
  imageserver:
    build:
      context: ./server/imageServer
      dockerfile: Dockerfile
    container_name: imageserver
    restart: always
    expose:
      - "3002"
    networks:
      - front-connection
  
